isPartial: False
partialexpname: dvmatcher_faust_partial

expname: dvmatcher_faust

dataset: faust

deform_mesh: False

loss:
  k_deform: 10
  
# misc
misc:
  cuda: True
  device: 0
  checkpoint_interval: 1
  log_interval: 5000