isPartial: False
partialexpname: dvmatcher_shrec_19_partial

expname: dvmatcher_shrec_19

dataset: shrec_19

deform_mesh: False

loss:
  k_deform: 10
  
# misc
misc:
  cuda: True
  device: 0
  checkpoint_interval: 1
  log_interval: 5000